name: 🐛 Bug report
description: Report a bug
labels: Bug report
assignees:
  - pratyakshm
body:
  - type: dropdown
    id: category
    attributes:
      label: Select category
      description: Which category is this issue filed against?
      multiple: false
      options:
        - "Apps"
        - "Features"
        - "Privacy"
        - "Security"
        - "Tasks"
        - "Services"
        - "Windows Explorer / User Interface"
    validations:
      required: true
  - type: dropdown
    id: winver
    attributes:
      label: Windows version
      description: "Check all that apply."
      multiple: true
      options:
         - "Windows 11 21H2"
         - "Windows 10 21H2"
         - "Windows 10 21H1"
         - "Windows 10 20H2"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: WinRice output
      description: WinRice output is saved in C:\WinRice. Copy paste the output of the output file here.
    validations:
      required: true
  - type: checkboxes
    id: similar
    attributes:
      label: Alternative software run
      description: Check this box if you have run alternative software similar to WinRice
      options:
        - label: "I have run alternative software that offers functionality similar to WinRice"
          required: false
  - type: textarea
    id: similarlink
    attributes:
      label: Link to alternative similar software
      description: Provide link to alternative software which you have run.
    validations:
      required: false
  
