name: 🐛 Bug report
description: File a bug report
title: "Bug: "
labels: Issue-Bug
assignees:
  - pratyakshm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to file this report.
  - type: dropdown
    id: version
    attributes:
      label: WinRice version
      description: Check all that apply.
      multiple: true
      options:
        - main branch
        - v0.4 August release
    validations:
      required: true
  - type: dropdown
    id: Windows-version
    attributes:
      label: Windows version
      multiple: true
      description: Check all that apply.
      multiple: true
      options: 
        - Windows 10 21H1
        - Windows 11 21H2
    validations:
      required: true
  - type: textarea
    id: osbuild
    attributes:
      label: Write absolute OS build version
      description: Run this command in PowerShell - `Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Update\TargetingInfo\Installed\Client.OS.rs2.amd64" -Name Version` 
      placeholder: Raw output of the command.
  - type: dropdown
    id: category
    attributes:
      label: Which category is the issue related to?
      description: Check all that apply.
      multiple: true
      options:
        - Apps and Features
        - Privacy and Security
        - Tasks and Services
        - Windows UI
        - Other
    validations: 
      required: true   
  - type: dropdown
    id: areaofconcern
    attributes: 
      label: Does something on the OS break or does WinRice functionality not work?
      description: Does something break on the Operating System after running WinRice, or does a particular WinRice functionality not work?
      multiple: false
      options:
        - WinRice not working as expected
        - Something wrong with OS after running WinRice
    validations: 
      required: true
  - type: textarea
    id: expectedbehavior
    attributes:
      label: ✔️ Expected Behavior
      placeholder: Tell us what was expected to happen.
    validations:
      required: false
  - type: textarea
    id: actualbehavior
    attributes:
      label: ❌ Actual Behavior
      placeholder: What actually happened?
    validations: 
      required: true
  - type: textarea
    id: stepstorepro
    attributes:
      label: Steps to reproduce
      description: Tell us the steps required to trigger your bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: PowerShell transcript output
      description: Please copy and paste the PowerShell transcript output. You may get it from "C:\WinRice" folder.
      placeholder: PowerShell transcript comes here.
      render: powershell
  - type: textarea
    id: othersoftware
    attributes: 
      label: Other software run
      description: Tell us about other similar software you ran on your device (if any).
      placeholder: "Paste repository link. Do know that support might be limited if you run other software of similar kind."
    validations:
      required: false
