name: 🐛 Bug report
description: Report a bug
labels: Bug report
assignees:
  - pratyakshm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to file this report.
  - type: dropdown
    id: winver
    attributes:
      label: Windows version
      description: "Check all that apply."
      multiple: true
      options:
         - "Windows 11, version 22H2 (Fall 2022 Update)"
         - "Windows 11, version 21H2 (Original Release)"
         - "Windows 10, version 21H2 (November 2011 Update)"
         - "Windows 10, version 21H1 (May 2021 Update)"
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: WinRice output
      description: Copy paste or drag and drop below the transcript files logged by WinRice in C:\WinRice. Paste only the file(s), not their content.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Anything else I should know?
      description: Additional stuff you think I should know. 
    validations:
      required: false
  
