name: 📃 Documentation issue
description: File an issue with documentation
title: "Docs issue: "
labels: Issue-Docs
assignees:
  - pratyakshm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to file this report.
  - type: textarea
    id: location
    attributes:
      label: Concerned doc
      description: Provide link to the concerned doc.
    validations: 
      required: true   
  - type: textarea
    id: explaintheissue
    attributes:
      label: Explain the issue
      description: Explain the issue with proper details.
    validations:
      required: true
  - type: textarea
    id: proposedchanges
    attributes:
      label: Proposed changes (optional)
      description: Provide proposed / suggested changes to the doc.
    validations:
      required: false