name: 📃 Documentation issue
description: File an issue with documentation
labels: Documentation issue
assignees:
  - pratyakshm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to file this report.
  - type: input
    id: location
    attributes:
      label: Concerned document
      description: Provide link to the concerned document.
    validations: 
      required: true   
  - type: textarea
    id: explaintheissue
    attributes:
      label: Explain the issue
      description: Explain the issue with proper details.
    validations:
      required: true
  - type: textarea
    id: proposedchanges
    attributes:
      label: Proposed changes
      description: What changes do you propose for the document?
    validations:
      required: true