name: 🚀 Feature request
description: Request a feature
labels: Feature request
assignees:
  - pratyakshm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to file this feature request.
  - type: checkboxes
    id: principles
    attributes:
      label: WinRice principles
      description: https://github.com/pratyakshm/WinRice/wiki/Principles
      options:
        - label: "I have read the WinRice principles and I believe that this feature request abides by the WinRice principles to my truest sense."
          required: true
  - type: textarea
    id: explain1
    attributes:
      label: Explain the feature.
      description: Please explain the feature in as much detail as you can. Providing screenshots, if helpful, is highly appreciated.
    validations:
      required: true
  - type: dropdown
    id: question2
    attributes:
      label: Does your feature request involve usage of third party software?
      description: Know that feature requests which suggest usage of third party software are often low prioritized. Exceptions apply.
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true