name: 🚀 Feature request
description: Request a feature
labels: Feature request
assignees:
  - pratyakshm
body:
  - type: dropdown
    id: question
    attributes:
      label: Does your feature request involve usage of third party software?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: question2
    attributes:
      label: Have you written the code that adds this feature?
      multiple: false
      options:
         - "Yes"
         - "No"
    validations:
      required: true
  - type: textarea
    id: explain
    attributes:
      label: Explain the feature
      description: Describe it in as much detail as possible.
      placeholder: Provide screenshots and/or code snippets if you can.
    validations:
      required: true
  - type: checkboxes
    id: principles
    attributes:
      label: Does this Feature Request follow the WinRice principles?
      description: https://github.com/pratyakshm/WinRice/wiki/Principles
      options:
        - label: "Yes"
          required: true
  
